In [36]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [37]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_Database.csv")
city_data_df.tail()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
689,689,bahia honda,CU,22.90,-83.16,78.48,86,9,11.30,clear sky,2020-11-02 02:52:22
690,690,whyalla,AU,-33.03,137.58,86.00,27,1,11.41,clear sky,2020-11-02 02:52:22
691,691,beruwala,LK,6.48,79.98,82.36,70,0,2.80,clear sky,2020-11-02 02:52:23
692,692,san rafael,AR,-34.62,-68.33,69.60,24,50,6.04,scattered clouds,2020-11-02 02:52:23
693,693,porto velho,BR,-8.76,-63.90,77.00,94,0,2.24,clear sky,2020-11-02 02:52:13

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 65

In [5]:
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the maximum temperature you would like for your trip? 80

In [6]:
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
2,2,puerto ayora,EC,-0.74,-90.35,69.01,91,100,4.00,overcast clouds,2020-11-02 02:42:34
12,12,saint george,US,37.10,-113.58,66.20,14,1,6.93,clear sky,2020-11-02 02:46:04
13,13,aguimes,ES,27.91,-15.45,71.60,60,0,16.11,clear sky,2020-11-02 02:50:58
14,14,rikitea,PF,-23.12,-134.97,73.85,86,91,24.32,overcast clouds,2020-11-02 02:46:33
15,15,cabo san lucas,MX,22.89,-109.91,79.00,72,0,5.66,clear sky,2020-11-02 02:50:58
16,16,camocim,BR,-2.90,-40.84,77.92,86,64,8.84,broken clouds,2020-11-02 02:50:58
17,17,avarua,CK,-21.21,-159.78,78.80,83,93,17.22,light rain,2020-11-02 02:50:58
18,18,kisangani,CD,0.52,25.20,69.60,98,100,1.50,light rain,2020-11-02 02:50:58
28,28,carnarvon,AU,-24.87,113.63,73.40,49,40,16.11,scattered clouds,2020-11-02 02:50:59
33,33,bilma,NE,18.69,12.92,66.97,30,0,11.56,clear sky,2020-11-02 02:51:00

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.notnull().sum()

City_ID                212
City                   212
Country                209
Lat                    212
Lng                    212
Max Temp               212
Humidity               212
Cloudiness             212
Wind Speed             212
Current Description    212
Date                   212
dtype: int64

In [8]:
preferred_cities_df.count()

City_ID                212
City                   212
Country                209
Lat                    212
Lng                    212
Max Temp               212
Humidity               212
Cloudiness             212
Wind Speed             212
Current Description    212
Date                   212
dtype: int64

In [9]:
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                3
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
Date                   0
dtype: int64

In [10]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
2,2,puerto ayora,EC,-0.74,-90.35,69.01,91,100,4.00,overcast clouds,2020-11-02 02:42:34
12,12,saint george,US,37.10,-113.58,66.20,14,1,6.93,clear sky,2020-11-02 02:46:04
13,13,aguimes,ES,27.91,-15.45,71.60,60,0,16.11,clear sky,2020-11-02 02:50:58
14,14,rikitea,PF,-23.12,-134.97,73.85,86,91,24.32,overcast clouds,2020-11-02 02:46:33
15,15,cabo san lucas,MX,22.89,-109.91,79.00,72,0,5.66,clear sky,2020-11-02 02:50:58
...,...,...,...,...,...,...,...,...,...,...,...
681,681,iseyin,NG,7.97,3.60,72.23,98,18,3.22,few clouds,2020-11-02 02:52:21
684,684,guanare,VE,9.04,-69.74,73.45,92,100,1.19,overcast clouds,2020-11-02 02:52:21
689,689,bahia honda,CU,22.90,-83.16,78.48,86,9,11.30,clear sky,2020-11-02 02:52:22
692,692,san rafael,AR,-34.62,-68.33,69.60,24,50,6.04,scattered clouds,2020-11-02 02:52:23
693,693,porto velho,BR,-8.76,-63.90,77.00,94,0,2.24,clear sky,2020-11-02 02:52:13

In [11]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,puerto ayora,EC,69.01,overcast clouds,-0.74,-90.35,
12,saint george,US,66.20,clear sky,37.10,-113.58,
13,aguimes,ES,71.60,clear sky,27.91,-15.45,
14,rikitea,PF,73.85,overcast clouds,-23.12,-134.97,
15,cabo san lucas,MX,79.00,clear sky,22.89,-109.91,
16,camocim,BR,77.92,broken clouds,-2.90,-40.84,
17,avarua,CK,78.80,light rain,-21.21,-159.78,
18,kisangani,CD,69.60,light rain,0.52,25.20,
28,carnarvon,AU,73.40,scattered clouds,-24.87,113.63,
33,bilma,NE,66.97,clear sky,18.69,12.92,

In [12]:
len(hotel_df)

212

In [13]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [14]:
# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": g_key
    }

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
        
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.

In [16]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,puerto ayora,EC,69.01,overcast clouds,-0.74,-90.35,Puerto Ayora
12,saint george,US,66.20,clear sky,37.10,-113.58,St. George
13,aguimes,ES,71.60,clear sky,27.91,-15.45,"Ingenio, Las Palmas"
14,rikitea,PF,73.85,overcast clouds,-23.12,-134.97,Rikitea
15,cabo san lucas,MX,79.00,clear sky,22.89,-109.91,Cabo San Lucas

In [29]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [30]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [31]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

In [32]:
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))